name: Unittest
on: [ push ]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ Run tests. ${{ github.event_name }} event."
      - uses: php-actions/composer@v5
        with:
          dev: no
          args: --profile --ignore-platform-reqs