name: Unittest
on: [ push ]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Run tests. ${{ github.event_name }} event."
      - name: Check composer.json
        run: composer validate --strict
      - name: Install dependencies
        run: composer install
