name: Unittest
on: [ push ]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ Run tests. ${{ github.event_name }} event."
      - name: Check composer.json
        run: composer validate --strict --working-dir=../../
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=../../
